import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Dynamic theme colors (CSS variables)
        primary: 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary-container': 'var(--color-on-primary-container)',
        secondary: 'var(--color-secondary)',
        'on-secondary': 'var(--color-on-secondary)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        tertiary: 'var(--color-tertiary)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        surface: 'var(--color-surface)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'surface-tint': 'var(--color-surface-tint)',
        'surface-variant': 'var(--color-surface-variant)',
        background: 'var(--color-background)',
        'on-background': 'var(--color-on-background)',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        error: 'var(--color-error)',
        'on-error': 'var(--color-on-error)',
        'error-container': 'var(--color-error-container)',
        'on-error-container': 'var(--color-on-error-container)',
        // Elite Gold Accents
        'stark-gold': '#d4af37',
        'stark-gold-light': '#ffe088',
        'stark-gold-dim': '#e9c349',
        // Status Colors
        success: '#4ade80',
        warning: '#fbbf24',
        info: '#3b82f6',
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        // Elite Dark Theme Typography (Inter)
        'display-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        // High-End Gallery Light Theme Typography
        'light-display': ['Libre Caslon Text', 'serif'],
        'light-body': ['Hanken Grotesk', 'sans-serif'],
        // Fallbacks
        sans: ['Inter', 'Hanken Grotesk', 'sans-serif'],
        serif: ['Libre Caslon Text', 'serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        // Elite Dark Theme Typography
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.02em', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
        // High-End Gallery Light Theme Typography
        'light-display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'light-display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'light-headline-lg': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'light-headline-md': ['24px', { lineHeight: '32px', fontWeight: '400' }],
        'light-body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0.01em', fontWeight: '400' }],
        'light-body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'light-label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'light-label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      spacing: {
        unit: '8px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'container-padding-mobile': '24px',
        'container-padding-desktop': '40px',
        'container-padding-desktop-light': '64px',
        gutter: '16px',
        'gutter-light': '24px',
      },
      backdropBlur: {
        xs: '4px',
        '4xl': '80px',
      },
      boxShadow: {
        // Elite Dark Theme Shadows
        'glass': '0px 10px 30px rgba(192, 192, 192, 0.02)',
        'glass-gold': '0px 10px 40px rgba(233, 195, 73, 0.05)',
        'silver-glow': '0px 10px 30px rgba(192, 192, 192, 0.05)',
        'gold-glow': '0 0 20px rgba(233, 195, 73, 0.2)',
        'gold-glow-lg': '0 0 40px rgba(233, 195, 73, 0.3)',
        'premium-card': 'inset 0 1px 0 rgba(255,255,255,0.1), 0 20px 40px rgba(0,0,0,0.8)',
        // High-End Gallery Light Theme Shadows
        'ambient': '0px 10px 40px rgba(0, 0, 0, 0.03)',
        'ambient-lg': '0px 20px 60px rgba(0, 0, 0, 0.04)',
        'hairline': '0px 4px 30px rgba(0,0,0,0.02)',
        'gallery-lift': '0px 30px 80px rgba(0,0,0,0.06)',
      },
      transitionTimingFunction: {
        'premium': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
        'elite': 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
        'gallery': 'cubic-bezier(0.4, 0.0, 0.2, 1)',
      },
      animation: {
        'fade-in': 'fadeIn 0.6s cubic-bezier(0.2, 0.8, 0.2, 1)',
        'slide-up': 'slideUp 0.5s cubic-bezier(0.2, 0.8, 0.2, 1)',
        'scale-in': 'scaleIn 0.4s cubic-bezier(0.2, 0.8, 0.2, 1)',
        'pulse-gold': 'pulseGold 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'glass-shimmer': 'glassShimmer 3s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'glow-pulse': 'glowPulse 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideUp: { from: { opacity: '0', transform: 'translateY(24px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn: { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        pulseGold: { '0%, 100%': { boxShadow: '0 0 10px rgba(233,195,73,0.2)' }, '50%': { boxShadow: '0 0 30px rgba(233,195,73,0.5)' } },
        shimmer: { from: { backgroundPosition: '-200% 0' }, to: { backgroundPosition: '200% 0' } },
        glassShimmer: {
          '0%, 100%': { backgroundPosition: '-200% 0' },
          '50%': { backgroundPosition: '200% 0' }
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' }
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(212, 175, 55, 0.2)' },
          '50%': { boxShadow: '0 0 40px rgba(212, 175, 55, 0.4)' }
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
